# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/bless/cnn_detection/cnn_detection.runs/synth_1/TOP_integration_uart.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bless/cnn_detection/cnn_detection.cache/wt [current_project]
set_property parent.project_path C:/Users/bless/cnn_detection/cnn_detection.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kr260_som:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/bless/cnn_detection/cnn_detection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/CSC_encoder/CSC_encoderr.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/CSC_encoder/CSC_encoderr_FIFO.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Cluster_Group/Cluster_Group.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Cluster_Group/Cluster_Group_Controller.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Cluster_Group/Cluster_Group_array.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/SPad/Former_addr_Spad.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/SPad/Former_data_Spad.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/GLB_Cluster/GLB_Cluster.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Router_Cluster/Iact_Router.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/GLB_Cluster/Iact_SRAM_Bank.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/GLB_Cluster/Iact_addr_SRAM.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/GLB_Cluster/Iact_data_SRAM.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/SPad/Later_addr_Spad.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/SPad/Later_data_Spad.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Pooling/Max_pooling.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE_Cluster.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE_Cluster_Data_Connections.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE_Cluster_controller.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/PE_data_FIFO.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/PE_psum_FIFO.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/Processing_Element.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/Processing_Element_Controller.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/Processing_Element_core.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Quantizer/Psum_Requantizer.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Router_Cluster/Psum_Router.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/GLB_Cluster/Psum_SRAM_Bank.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/Psum_SRAM_out_acc.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/PE_Cluster/PE/SPad/Psum_Spad.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/Psum_rearrange.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Activation/ReLU.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Router_Cluster/Router_Cluster.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Activation/Softmax.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/TOP.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/TOP_controller.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/TOP_interface.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/Router_Cluster/Weight_Router.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/IO_processing/clock_gen.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/im2col_converter/im2col_converter.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/IO_processing/interrupt_gen.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/display/seg7_encoder.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/UART/start_en_detect.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/UART/uart_module.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/UART/RX/uart_rx_band_gen.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/UART/RX/uart_rx_ctl.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/UART/RX/uart_rx_module.v}
  {C:/Users/bless/Downloads/BoooC CNN-Accelerator-Based-on-Eyeriss-v2 master FPGA_design-src/TOP/TOP_integration_uart.v}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bless/Downloads/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/bless/Downloads/constraints.xdc]

read_xdc C:/Users/bless/Downloads/pynq_z2_example.xdc
set_property used_in_implementation false [get_files C:/Users/bless/Downloads/pynq_z2_example.xdc]

read_xdc C:/Users/bless/Downloads/uart2.xdc
set_property used_in_implementation false [get_files C:/Users/bless/Downloads/uart2.xdc]

read_xdc C:/Users/bless/Downloads/uart.xdc
set_property used_in_implementation false [get_files C:/Users/bless/Downloads/uart.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/bless/cnn_detection/cnn_detection.srcs/utils_1/imports/synth_1/TOP_integration_uart.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TOP_integration_uart -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_integration_uart.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file TOP_integration_uart_utilization_synth.rpt -pb TOP_integration_uart_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
